USE TEST1;

CREATE TABLE TB_USER(

USER_NO INT PRIMARY KEY auto_increment,

USER_ID VARCHAR(50) UNIQUE NOT NULL,

USER_NAME VARCHAR(50) NOT NULL,

USER_AGE INT NOT NULL

);


INSERT INTO TB_USER(USER_ID, USER_NAME, USER_AGE) VALUES('gd_hong', '홍길동', 20);

INSERT INTO TB_USER(USER_ID, USER_NAME, USER_AGE) VALUES('sh_han', '한소희', 28);

INSERT INTO TB_USER(USER_ID, USER_NAME, USER_AGE) VALUES('jm_park', '지민', 27);
